### ISSUE TITLE
Allow for queue_url to be passed in

### ISSUE THREAD

**Issue by golmansax** [jegesh/python-sqs-listener#14]
Any reason not to allow `queue_url` to be passed in rather than `queue_name`?  If you are okay with supporting it, I can draft a pull request.

**Comment by jegesh** [comment]
If you mean adding a second constructor alongside the original one, then I
agree.

I think in most cases people don't have the queue url on hand, they just
know the name, therefore up 'til now there was no demand for this. Put if
you need it, by all means, make a pull request!

**Comment by golmansax** [comment]
Thanks for getting back.  What would a second constructor look like, Python doesn't support that by default?  I was thinking there could be a check so that if in `__init__(self, queue)` and `queue` is a URL, then bypass the URL lookup by queue name.

**Comment by jegesh** [comment]
Good point. I guess your suggestion is a valid solution. See [here](
https://stackoverflow.com/questions/44765482/multiple-constructors-the-pythonic-way?noredirect=1&lq=1)
and [here](
https://stackoverflow.com/questions/141545/how-to-overload-init-method-based-on-argument-type)
for more 'pythonic' solutions.

**Comment by golmansax** [comment]
Hi, sorry for not responding to this sooner.  We ended up forking the library because we had a few more changes that needed to be made, but will submit a pull if we end up making the code more generic.

**Comment by jegesh** [comment]
Pull request? No pressure, this is just for your own sake.
