### ISSUE TITLE
Make deletion of queue message optional even in success cases

### ISSUE THREAD

**Issue by johngriebel** [jegesh/python-sqs-listener#15]
Hi,
I'm currently developing using `python-sqs-listener`, and I've found myself wishing that deleting a queue message after `handle_message` was optional even when `handle_message` runs without raising an exception. I envision using this feature almost exclusively during development, but maybe there are use cases that don't want the message deleted after processing even in production code. I would be more than willing to submit a pull request, but I wanted to check in and see how this idea might be received. Thoughts?

**Comment by jegesh** [comment]
I honestly can't imagine a reasonable use case. I think if you are leaving
messages in the queue after processing, then you're not actually using SQS
as a message queue, and you might want to reconsider using it. (the fact
that this is the only behavior available for the last 18 months of a
moderately used package, and you're the first person to need this, also
speak for itself)

**Comment by johngriebel** [comment]
Like I said, I've only personally wished for this during development to test worker code that processes messages. That's fine though, I'm going to close the issue.
