### ISSUE TITLE
Allow use of separate AWS credentials

### ISSUE THREAD

**Issue by acidbotmaker** [jegesh/python-sqs-listener#33]
Is it possible to add feature to use aws credentials from either .env file or in constructor?

**Comment by raminsj13** [comment]
perhaps via the "profile" parameter in botocore/session.py?

**Comment by jegesh** [comment]
A PR would be awesome if this is still an issue! (if not please close)

**Comment by jegesh** [comment]
Btw if you have the AWS credentials in an `.env` file you can just `source` it before you run the listener itself:
`source .env && python listener.py`

**Comment by jegesh** [comment]
@raminsj13 since the listener relies on `boto` for resolving credentials, just setting the `AWS_PROFILE` environment variable should allow you to choose the profile you want to use for the listener.  Have you tried that?

**Comment by acepace** [comment]
@jegesh your code forces the default session to be an IAM role rather than allowing it to use files.

**Comment by seandickert** [comment]
Would a better, and easier, solution to be just change the SqsListener object to take the boto3 session object as constructor parameter? Allows the user to decide how to initialize the AWS connection, which is probably how it should be. I can't think of a reason why the package should care how the connection is established.

To keep it backwards compatible, it could be passed in the kwargs object and default to current path if not available.

**Comment by acepace** [comment]
I forked the project, if there's interest
