### ISSUE TITLE
How to run this daemon in docker container?

### ISSUE THREAD

**Issue by TechHoops** [jegesh/python-sqs-listener#35]
Hi All,
 I'm trying to run this listener in docker with the following ENTRYPOINT but container is not staying alive. please help what I'm doing wrong

ENTRYPOINT python3 /data/gdal_listener.py start &

**Comment by jegesh** [comment]
Did you manage to resolve this?
What does your code in `gdal_listener.py` look like?  If that's the daemon file you can probably skip the whole thing and just run the listener entrypoint directly with a `&` after it.
(Btw if you're running GDAL and python in docker you may want to check out my image: [https://hub.docker.com/r/jegesher/gdal-python](https://hub.docker.com/r/jegesher/gdal-python))
