### ISSUE TITLE
Release source distribution besides wheel

### ISSUE THREAD

**Issue by apregoe** [jegesh/python-sqs-listener#36]
Hi, I am using an internal tool that cannot import wheel files. Can you also release the source code as well (aka. tar.gz file)? Just like requests does (url below). Thanks

https://pypi.org/project/requests/#files

**Comment by jegesh** [comment]
Sorry I have neglected this. Let me know if you still need this and I'll try to take care of it soon.

**Comment by jegesh** [comment]
If anyone wants to help by explaining to me the difference between an archive file you download from pypi and a zipped clone of the repo from Github, I'd be very grateful.
