### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by aschuhl** [jegesh/python-sqs-listener#4]
When using the example I get the following error:

`  File "t.py", line 7
    listener = MyListener('my-message-queue', error_queue='my-error-queue', region_name='us-east-1')
           ^
SyntaxError: invalid syntax`

Using Python 2.7.10 and pySqsListener 0.6.7

**Comment by jegesh** [comment]
Can you give me the full stack trace for the error?

**Comment by aschuhl** [comment]
That is the full stack trace

**Comment by jegesh** [comment]
Looks like a closing parenthesis is missing at the end of the previous line of the example code. I'll try to fix the readme in the next couple of days. Thanks for pointing out this issue, and please let me know if that solves the problem.
