### ISSUE TITLE
`continue` statement in while loop for listener

### ISSUE THREAD

**Issue by hjpotter92** [jegesh/python-sqs-listener#41]
https://github.com/jegesh/python-sqs-listener/blob/master/sqs_listener/__init__.py#L151

I think the `continue` statement will break the flow of code execution:

``` python
            if 'Messages' in messages:
                sqs_logger.debug(messages)
                continue
                sqs_logger.info("{} messages received".format(len(messages['Messages'])))
```

**Comment by jegesh** [comment]
good catch. This was accidentally included in a PR from a few days ago. Now fixed.  I didn't push these changes to pypi, in any case
