### ISSUE TITLE
State of this repository ?

### ISSUE THREAD

**Issue by ypicard** [jegesh/python-sqs-listener#52]
Hi,

This repository has not have any commits for the last 14 months. I would like to know if it is still maintained and accepting new pull requests / feature requests.

Thank you

**Comment by jegesh** [comment]
Well, as you noticed, I'm not really paying it the attention it deserves, but I'm trying to get around to reviewing the many pending PRs in the next few weeks.

Would you like to join as a maintainer?

**Comment by ypicard** [comment]
I could be interested indeed. What would this involve?

**Comment by jegesh** [comment]
Mostly just reviewing PRs, making sure they don't hinder or degrade the basic functionality of the package, and make sure any changes make it to the readme, and then merge them. I'll push the new versions to pypi.

Btw your website is inaccessible due to security errors

**Comment by ypicard** [comment]
I'm in. Just so you know, this would be my first time participating in an open-source project like this one. I''ll be all ears on your feedback anytime you have some. 

And yes, haven't looked at my website for a while. Thanks!

**Comment by jegesh** [comment]
The most important thing as far as I'm concerned is not to introduce new bugs when merging PRs, like this one 
https://github.com/jegesh/python-sqs-listener/issues/53

I fixed that one already, but as you can see it came from me trusting an innocent PR that was untested.
