### ISSUE TITLE
UnboundLocalError: local variable 'boto3_session' referenced before assignment

### ISSUE THREAD

**Issue by SohailChamadia-everestek** [jegesh/python-sqs-listener#53]
The newly added support for passing the AWS access credentials as keyword arguments in case it is not passed through environment variables

https://github.com/jegesh/python-sqs-listener/pull/34

Need to handle the if loop for boto3_session since it is initialized conditionally

**Comment by caioluciofc** [comment]
Got the same bug, downgraded to 0.8.7, worked fine. :)

**Comment by dashsatish** [comment]
@jegesh this is breaking in 0.8.9.

**Comment by jegesh** [comment]
Thanks all for the heads up, I'll try to get a fix in tonight

**Comment by jegesh** [comment]
Fixed in v0.8.10
