### ISSUE TITLE
Unnecessarily fails when AWS credentials method is 'assume-role-with-web-identity'

### ISSUE THREAD

**Issue by jindalrj** [jegesh/python-sqs-listener#54]
In EKS environments, each container on a single host can have its own credentials. Authentication is supported via a mechanism of 'serviceAccounts' (a kubernetes term). 

`boto3.Session().get_credentials().method` returns `assume-role-with-web-identity` which is another form of iam role based credentials.

Current implementation only allows `iam-role`, `assume-role` but not 'assume-role-with-web-identity'.

**Comment by LDderlee** [comment]
is there any update on this failure? I have the exact same problem @jegesh

**Comment by josemlp91** [comment]
https://github.com/jegesh/python-sqs-listener/pull/57/files
